export const apiendpoints = {
  getBoardingPassData:( bookingId:any,
    identification:any)=> `/booking/getTouristTicketByDocument?bookingId=${bookingId}&identification=${identification}`,
  getShiftsAndTicketTypesByPlace: "/booking/tickets",
  getPlaceQuickLinks: "/place/getPlaceDetails",
  GetBookingDetails: "/booking",
  GetUserBookingIdDetails: "/operator",
  createBookigByPlace: "/booking/create/v2",
  createBookigByPlaceV1: "/booking",
  getAddonItemsByTicketId: "/booking/addon",
  getTicketTypeConfigDataByTicketId: "/booking/ticket-config",
  confirmBookingById: "/booking/confirm/v2",
  confirmBookingByIdV1: "/booking/confirm",
  GetBookingStatus: "/booking/payment/verification",
  cancelBookingById: "/booking/refund/v2",
  guestLogin: "/guest/login",
  GuestUpdateMobileNumber: "/guest/update-mobile",
  guestVerifyOtp: "/guest/verify",
  guestSignUp: "/guest/signup",
  checkMobileNo: "/guest/check-mobile",
  getUserDetail: (id: string) => `/user/${id}`,
  getInvoiceDataForBooking: "/booking/get-invoice-v1",
  getInvoiceForChoiceBooking:'/choiceAddOn/getInvoice',
  getInvoiceForDifferentAmount:'/differenceAmount/getInvoice',
  getOBMSIdForBooking: "/place/get",
  getChatBotTransactionData: "/chatbot/conversation",
  getChatBotCancelledData: "/chatbot/booking/cancelled",
  getChatBotBookingAction: "/chatbot/booking/action",
  getAllSpecificCharges: "/specific-charges",
  getInventoryDataByPlace: "/booking/inventory",
  getQuotaDataByInventory: "/booking/quota",
  getAllBookingIds:( searchBookingIdValue:any,
    userId:any)=> `/helpdesk/getAll-bookings?bookingId=${searchBookingIdValue}&id=${userId}`,
  getPlaceList:( districtId:any,
    searchKey:any,departmentId:any)=> `/place/placeFilters?districtId=${districtId}&searchKey=${searchKey}&departmentId=${departmentId}`,
  getBookingId:( placeId:any,
    issueType:any,size:any,offset:any,pagination:any)=> `/helpdesk/userIssue?placeId=${placeId}&issueType=${issueType}&size=${size}&offset=${offset}&pagination=${pagination}`,
  getUserIssueResult:( bookingId:any,
    issueType:any)=> `/helpdesk/userIssue/on?bookingId=${bookingId}&issueType=${issueType}`,
  getDownloadTicketById: (bookingId: any) => `/helpdesk/getBookingDetail?bookingId=${bookingId}`,
  getAllHelpDeskListing: (search: string, statusList: string[]) =>
    `/helpdesk/getAll-tourist-tickets?&searchKey=${search}&statusList=${statusList}`,
  getAllHelpDeskNotificationCountes: (search: string, statusList: string) =>
    `/helpdesk/getAll-tourist-tickets?&searchKey=${search}&statusList=${statusList}`,
  helpdeskAttachment: "/file/helpdesk-files-upload",
  createHelpDesk: "/helpdesk/create-help-desk",
  createMessage: "/helpdesk/open-chat",
  getHelpDeskChatById: (id: any) => `/helpdesk/getChat/${id}`,
  getHelpDeskChatSeen: (id: any) => `/helpdesk/seenChat/${id}`,
  getHelpDeskDetailById: (id: any) => `/helpdesk/getById/${id}`,
  getBoardingPdf: (bookingId: string, boardingPassId: string) =>
    `/boardingV2/invoiceV2?bookingId=${bookingId}&boardingPassId=${boardingPassId}`,
  getUserDetailsByMobileNo:(
    searchMobileIdValue:any)=> `/helpdesk/guest-user-details?mobile=${searchMobileIdValue}`,
    getPackageForBooking:"/package/get-place",
    getTicketTypesByPackageId:"/package/management/tickets",
    createPackageBooking:"/package/management/create/v2",
    confirmPackageBookingById:"/booking/confirm/v2",
    getCompositeInvoiceForBooking: "/package/management/get-package-invoice",
    createNewVendor:"/vendor/create-vendor",
    getVendorTypeAllStatus:"/vendor/getAllVendors",
    getVendorTypeById:"vendor",
    getMasterVendorType: "/master/vendor/type",
    approveRejectVendor:"vendor/approve",
    checkRefundable:"/booking/check-refundable/v2",
    getAllInventoryQuoteByPlaceId:"/ticket/config/getQuotaList",
    getInventoryDataList:"booking/quota/v2",
    profileAttachment: "/file/uploadProfile",
    webCheckIn:"/booking/check-in",
    bookingReverified:"/booking/ticketPaymentCheck",
    getVehicleDetail: (
      inventoryId: string,
      detail: boolean,
      getAll: boolean,
      zoneId: string,
      shiftId: string,
      date: string,
    ) =>
      `/boardingV2/vehicleV2?inventoryId=${inventoryId}&all=${detail}&getAll=${getAll}&zoneId=${zoneId}&shiftId=${shiftId}&date=${date}`,
    getAllGuides: (pageNumber: number, totalRecords: number, search: string, placeId:any,zoneId:any,shiftId:any,date:any) =>
      `/guide/getGuideListForChoice?offSet=${pageNumber}&size=${totalRecords}&searchKey=${search}&placeId=${placeId}&zoneId=${zoneId}&shiftId=${shiftId}&date=${date}`,
    getPriceDetails:"/choiceAddOn/getPriceDetails",  
    getPreferenceChoice:"/choiceAddOn/addChoiceAddOn",
    confirmBookingPreference:"/choiceAddOn/confirm",
    userSaveUserLogs:"/user/saveUserLogs",
    userSaveUserSteps:"/user/saveUserSteps",
    getAllZoneByPlaceId:"/zone/getZonePlaceWise",
    getTearmsCondition:"/t&c/all?placeId=",
    getAllShiftByPlaceId:"/shift/getShiftPlaceWise",
    getAllInventoryByPlaceId:"/booking/inventoryList",
    addEditReviewRating:'/reviewRating/addReviewRating',
    deleteReviewRating:'/reviewRating/deleteReviewRating',
    uploadReviewRating:'/file/uploadReviewRating',
    uploadVideo:'/file/uploadReviewRatingVideo',
    getAllTicketList:'/booking/getTicketList',
    getAllSeasonByPlaceId:'/season/getSeasonByDate',
    confirmPayDiffAmount:"/differenceAmount/confirm",
    ticketPaymentStatus:"/booking/ticketPaymentStatus",
    ticketPaymentCheck:"/booking/ticketPaymentCheck",
    changeBookingStatus:'/booking/updateBookingEmitraStatus',
    userLogsAttachmentApi: "/file/userLogsTextFile",
    getCancelledSeat:'/booking/getCancelledSeat',
    getIssueType:(placeId: any) => `/issue/get/types?placeId=${placeId}`,
    getAllBookings:( userId:any,)=> `/helpdesk/last/10?userId=${userId}`,
    getSubIssueType:(issueTypeId:any)=> `/issue/get/subTypes?issueTypeId=${issueTypeId}`,
    getEmitraKioskPaymentStatus:"/booking/getEmitraKioskPaymentStatus",
    getAllJkkCategory:"/jkk/allCategory",
    getAllJkkSubCategory:(categoryId:any)=> `/jkk/allSubCategory?categoryId=${categoryId}`,
    getAllJkkShift: (
    bookingStartDate: any,
    bookingEndDate: any,
    categoryId: any,
    subCategoryId: any) => `/jkk/getShift?bookingStartDate=${bookingStartDate}&bookingEndDate=${bookingEndDate}&categoryId=${categoryId}&subCategoryId=${subCategoryId}`,
    getAllJkkPlaceType:(subCategoryId:any)=> `/jkk/allType?subCategoryId=${subCategoryId}`,
    getJkkTicketTypeConfig:(typeId:any)=> `/jkk/allTicketTypeConfig?ticketTypeId=${typeId}`,
    createJkkBookig: "/jkk/create/booking",
    confirmJkkBookingById: "/jkk/confirm",
    getJkkTicketDetails:(startDay:any,
      endDay:any, dateType?:any, bookingId?:any)=> `/jkk/reportForUser?startDay=${startDay}&endDay=${endDay}&dateType=${dateType}&bookingId=${bookingId}`,
    getSsoStatus:"/booking/getSSOStatus",
    updateBankDetailsByTicketId: "/user/updateBankDetailsByBookingId?isFilter=true",
    getUserTicketListInLastTenMin: "/booking/getUserTicketListInLastTenMin",
    getJkkTicketPaymentCheck: "jkk/paymentCheck",
    checkJkkAvailability:"/jkk/check/availability",
    calenderAvilability:"/jkk/calender/availability",
    advanceAvailability:"/jkk/calender/advanceAvailability",
    advanceAvailabilityWithCategory:"/jkk/calender/advanceAvailabilityWithCategory",
    getAllJkkDetails:"/jkk/placeDetails",
    jkkAddBankDetails:"/jkk/addBankDetails",
    jkkProgramDetailOnAvailability:"/jkk/programDetails",
    getHotelAvlibilityById:"/hotel/getAvailableRoomOnDatesWithId",
    placeAvailabilityMothWise: "/booking/placeAvailabilityMothWise",
    jkkPriceCalculation:"/jkk/priceCalculation",
    getAllIgrpsCategory:"/igprgvs/getAllActiveCategories",
    checkIgAvailability:"/igprgvs/availability",
    advanceIgprsAvailability:"/igprgvs/calender/advanceAvailability",
     createIgprsBookig: "/igprgvs/createBooking",
     igprsPriceCalculation: "/igprgvs/priceCalculation",
     getIgprsReport: (startDay:any, endDay:any,userId:any) => `/igprgvs/report?startDay=${startDay}&endDay=${endDay}&userId=${userId}`,
     confirmIgprsBookingById: "/igprgvs/confirm",
     checkAvailablityAcRoom: "/igprgvs/availability",
     advanceIgprsAvailabilityWithCategory:"/igprgvs/calender/advanceAvailabilityWithCategory",
      getAsiPalceAvail: (placeId: any, date: any) => `/asi/placeAvail?placeId=${placeId}&date=${date}`,
      getAsiTicketDetailByPlace:"/booking/asiTickets",
      getAsiBookingPdf: (bookingId: any) => `/asi/pdf?bookingId=${bookingId}`,
      getAsiBookingDetails : "/asi/ticket",
      generateTicketPDF: "asi/generate-ticket-pdf",
      getTouristStats : "/home/district-report",
    };
