export const queryKeys = {
  getShiftsAndTicketTypesByPlace: "getShiftsAndTicketTypesByPlace",
  getPlaceQuickeLinks: "getPlaceQuickeLinks",
  GetBookingDetails: "GetBookingDetails",
  getAddonItemsByTicketType: "getAddonItemsByTicketType",
  GetUserBookingIdDetails: "GetUserBookingIdDetails",
  changeBookingStatus:'changeBookingStatus',
  checkBookingEmitraStatus:"checkBookingEmitraStatus",
  confirmBookingById: "confirmBookingById",
  cancelBookingById: "cancelBookingById",
  guestLogin: "guestLogin",
  GuestUpdateMobileNumber: "GuestUpdateMobileNumber",
  guestVerifyOtp: "guestVerifyOtp",
  guestSignUp: "guestSignUp",
  checkMobileNo: "checkMobileNo",
  getUserDetails: "getUserDetails",
  getInvoiceDataForBooking: "getInvoiceDataForBooking",
  getInvoiceForChoiceBooking:"getInvoiceForChoiceBooking",
  getInvoiceForDifferenceAmount:"getInvoiceForDifferenceAmount",
  getOBMSIdForBooking: "getOBMSIdForBooking",
  getAllSpecificCharges: "getAllSpecificCharges",
  getInventoryDataByPlace: "getInventoryDataByPlace",
  getQuotaDataByInventory: "getQuotaDataByInventory",
  getAllBookingId: "getAllBookingId",
  getUserIssueResult: "getUserIssueResult",
  getTicketDownloadById: "getTicketDownloadById",
  getAllPlace: "getAllPlace",
  getAllBookingsId: "getAllBookingsId",
  getAllHelpDeskListing:"getAllHelpDeskListing",
  GetAllHelpDeskNotificationCountes:"GetAllHelpDeskNotificationCountes",
  helpdeskAttachment:"helpdeskAttachment",
  createNewHelpTicket: "createNewHelpTicket",
  createMessage:"createMessage",
  getHelpDeskChatById:"getHelpDeskChatById",
  getHelpDeskChatBySeen:"getHelpDeskChatBySeen",
  getHelpDeskDetailById:"getHelpDeskDetailById",
  getUserDetailsByMobileNo:"getUserDetailsByMobileNo",
  getOBMSIdForPackageBooking:"getOBMSIdForPackageBooking",
  getTicketTypesByPackage:"getTicketTypesByPackage",
  createTicketPackageBooking:"createPackageBooking",
  confirmPackageBookingById:"confirmPackageBookingById",
  getCompositeInvoiceForBooking: "getCompositeInvoiceForBooking",
  createNewVendor:"createNewVendor",
getVendorTypeAllStatus:"getVendorTypeAllStatus",
getVendorTypeById:"getVendorTypeById",
getMasterVendorType:"getMasterVendorType",
approveRejectVendor:"approveRejectVendor",
checkRefundable:"checkRefundable",
getAllInventoryQuoteByPlaceId:"getAllInventoryQuoteByPlaceId",
getQuota:"getQuote",
profileAttachment:"profileAttachment",
getAllBoardingPassBookingPdf: "getAllBoardingPassBookingPdf",
webCheckIn:"webCheckIn",
bookingReverified:"bookingReverified",
getVehicleDetail:"getVehicleDetail",
getAllGuides:"getAllGuides",
getPriceDetails:"getPriceDetails",
getPreferenceChoice:"getPreferenceChoice",
saveUserLogs:"saveUserLogs",
saveUserSteps:"saveUserSteps",
getAllZoneByPlaceId:"getAllZoneByPlaceId",
getTearmsCondition:"getTearmsCondition",
getAllShiftByPlaceId:"getAllShiftByPlaceId",
getAllInventoryByPlaceId:"getAllInventoryByPlaceId",
addEditReviewRating:'addEditReviewRating',
deleteReviewRating:'deleteReviewRating',
uploadImage:'uploadImage',
uploadVideo:'uploadVideo',
getAllTicketList:"getAllTicketList",
getAllSeasonList:"getAllSeasonList",
getboardingPassdata:"getboardingPassdata",
requestId:"requestId",
getCancelledSeat:"getCancelledSeat",
chatBotTransactionData:"chatBotTransactionData",
chatBotCancelledData:"chatBotCancelledData",
chatBotAction:"chatBotAction",
getIssueType: "getIssueType",
getAllBookings: "getAllBookings",
getSubIssueType: "getSubIssueType",
getEmitraKioskPaymentStatus:"getEmitraKioskPaymentStatus",
getAllJkkCategory:"getAllJkkCategory",
getAllJkkSubCategory:"getAllJkkSubCategory",
getAllJkkShift:"getAllJkkShift",
getAllJkkPlaceType:"getAllJkkPlaceType",
getJkkTicketTypeConfig:"getJkkTicketTypeConfig",
getAllJkkDetails:"getAllJkkDetails",
getAllIgprsDetails:"getAllIgprsDetails",
createJkkBookig:"createJkkBookig",
confirmJkkBookingById: "confirmJkkBookingById",
getJkkTicketDetails:"getJkkTicketDetails",
getssoStatus:"getSsoStatus",
ticketPaymentStatus: "ticketPaymentStatus",
ticketPaymentCheck: "ticketPaymentCheck",
updateBankDetailsByTicketId: "updateBankDetailsByTicketId",
getUserTicketListInLastTenMin: "getUserTicketListInLastTenMin",
getJkkTicketPaymentCheck: "getJkkTicketPaymentCheck",
checkJkkAvailability:"checkJkkAvailability",
calenderAvilability:"calenderAvilability",
advanceAvailability:"advanceAvailability",
advanceIgprsAvailability:"advanceIgprsAvailability",
advanceAvailabilityWithCategory:"advanceAvailabilityWithCategory",
jkkAddBankDetails:"jkkAddBankDetails",
getHotelAvlibilityById: "getHotelAvlibilityById",
placeAvailabilityMothWise: "placeAvailabilityMothWise",
jkkPriceCalculation:"jkkPriceCalculation",
getAllIgrpsCategory:"getAllIgrpsCategory",

createIgprsBookig:"createIgprsBookig",
igprsPriceCalculation:"igprsPriceCalculation",
getIgprsReport:"getIgprsReport",
confirmIgprsBookingById: "confirmIgprsBookingById",
checkAvailablityAcRoom: "checkAvailablityAcRoom",
advanceIgprsAvailabilityWithCategory:"advanceIgprsAvailabilityWithCategory",
getAsiPalceAvail:"getAsiPalceAvail",
getAsiTicketDetailByPlace:"getAsiTicketDetailByPlace",
getAsiBookingPdf:"getAsiBookingPdf",
getAsiBookingDetails:"getAsiBookingDetails",
jkkProgramDetailOnAvailability :"jkkProgramDetailOnAvailability",
getTouristStats : "getTouristStats",
};
